# ~/.config/starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 1000
continuation_prompt = "â–¶â–¶"

#format = """ $localip$directory$character """
# format = """$username$env_var$hostname$directory$character"""
format = """$username$env_var$hostname$directory"""

# move the rest of the prompt to the right
right_format = """$all"""

[character]
success_symbol = "[âœ](green)"
# success_symbol = "[](white)"
error_symbol = "[âœ—](bold red)"

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](yellow)'
variable = "STARSHIP_DISTRO"

[localip]
ssh_only = false
format = '[$localipv4](white)'
#trim_at = ".companyname.com"
disabled = true

[hostname]
ssh_only = false
format = "[$hostname](light blue)" # [$ssh_symbol](bold purple)"
# trim_at = ".tomtiv.me"
disabled = false
# ssh_symbol ="ğŸŒ"


# Shows the username
[username]
style_user = "purple"
style_root = "bold red"
format = "[$user]($style)"
disabled = false
show_always = true

[directory]
truncation_length = 15
truncation_symbol = "â€¦/"
home_symbol = " ïŸ ~"
read_only_style = "bold red"
read_only = " ï€£"

[git_branch]
symbol = "ï¡ "
format = "via [$symbol$branch]($style) "
# truncation_length = 4
truncation_symbol = "â€¦/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "ğŸ³"
up_to_date = "ï† "
untracked = "ï”© "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ï£– "
modified = "ï„ "
staged = '[++\($count\)](green)'
renamed = "ïª¶ "
deleted = "ï€” "

[docker_context]
format = " [ïŒˆ $context](red) "
disabled = false

[nodejs]
format = "[ ï¢˜ $version](bold green) "
disabled = false

[python]
symbol = "ï Ÿ "
python_binary = "python3"
disabled = false

[ruby]
format = "via [îˆ¾ $version]($style) "
disabled = true
add_newline = true
command_timeout = 1000
continuation_prompt = "â–¶â–¶"

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ ïº $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[status]
style = 'blue'
# symbol = 'ğŸ”´ '
# success_symbol = 'ğŸŸ¢ SUCCESS'
format = '[$symbol$signal_name$maybe_int]($style) '
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[sudo]
style = "196"
symbol = "ğŸ’»"
disabled = true
